### PR TITLE
Publish tests

### PR DESCRIPTION
**Pull request by polyzen**
To be able to run the tests prior to installation, as part of building a distro package.

### CODE REVIEW

**Comment by RDCH106** [comment]
Thanks @polyzen !!

Could you change the PR target from master to develop??

**Comment by polyzen** [comment]
On November 22, 2018 2:47:02 AM EST, "Rubén de Celis Hernández" <notifications@github.com> wrote:
>Thanks @polyzen !!
>
>Could you change the PR from master to develop??
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/RDCH106/pycoinmon/pull/11#issuecomment-440941133

Will do.

-- 
Best,
polyzen

**Comment by polyzen** [comment]
First time trying to change the branch -- worked great:
https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/

**Comment by polyzen** [comment]
Something like this may also be needed:
https://github.com/pexpect/ptyprocess/pull/22/commits/1fa2011142a200563a9b8fbf303a622ab643cff8

**Comment by RDCH106** [comment]
@polyzen First of all sorry because my answer comes late. I was very busy the last months.

I have a couple reflexions about your PR:

- I am not sure if it is convenient to add tests to production package. I think that the test are relevant in develop stage or for CI, not for production.
- If the test are added, it is impossible the access to the test via terminal. The only way to use it making an import of the test and then execute it. For this purpose you need implement extra code.

What do you think? Do you still consider that the addition of the test to production package have any sense? Let me know if I am missing something and I am not taking in account the real reason of the proposed change.

Thanks in advance.

**Comment by polyzen** [comment]
> @polyzen First of all sorry because my answer comes late. I was very busy the last months.

No problem!

> I have a couple reflexions about your PR:
> 
>     * I am not sure if it is convenient to add tests to production package. I think that the test are relevant in develop stage or for CI, not for production.
> 
>     * If the test are added, it is impossible the access to the test via terminal. The only way to use it making an import of the test and then execute it. For this purpose you need implement extra code.

This is just to include the test in the PyPI package so it [can be run in the process of creating a distro package](https://wiki.archlinux.org/index.php/Creating_packages#check()).

> What do you think? Do you still consider that the addition of the test to production package have any sense? Let me know if I am missing something and I am not taking in account the real reason of the proposed change.
> 
> Thanks in advance.

**Comment by RDCH106** [comment]
I don´t know....

Is it really useful?

I think that the best way to do that is using the repository. Pypi package it is already a production package and generate a distro package from python production package it is also possible. But if you need test it, I think that it is better use repository instead of python production package.

**Comment by polyzen** [comment]
> If the test are added, it is impossible the access to the test via terminal. The only way to use it making an import of the test and then execute it. For this purpose you need implement extra code.

Works just fine with `python -m unittest discover tests`.

> I don´t know....
> 
> Is it really useful?
> 
> I think that the best way to do that is using the repository. Pypi package it is already a production package and generate a distro package from python production package it is also possible. But if you need test it, I think that it is better use repository instead of python production package.

Users may also want to see if the tests pass in their environment (eg. with different versions of deps than were tested upstream) or if they run into problems.

**Comment by RDCH106** [comment]
OK!

But the proposed changes don't show the call to execute the testing before running the process of creating a distro package. It only shows the inclusión of the test folder in the package and nothing more.

**Comment by polyzen** [comment]
> But the proposed changes don't show the call to execute the testing before running the process of creating a distro package.

It's done as a part of the process:
https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=pycoinmon&id=d7e284ce3e9475f40e47a6f1c0905d757ed7db1c

**Comment by polyzen** [comment]
Would you like me to mention `python -m unittest discover tests` in the commit message?

**Comment by RDCH106** [comment]
> 
> 
> > But the proposed changes don't show the call to execute the testing before running the process of creating a distro package.
> 
> It's done as a part of the process:
> https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=pycoinmon&id=d7e284ce3e9475f40e47a6f1c0905d757ed7db1c

Now I understand you!! 😅

If it is useful for ArchLinux I can add it.  But... the test only checks **errors according to the synthetic data given and expected as input**. For example, if the api of coinmarketcap changes, the test will not detect it. The test is **focused on the development to ensure that if other authors contribute don't break the functionality previously implemented**. Then, I am not sure if the test inclusion is useful.

**Comment by polyzen** [comment]
Gotcha!

**Pull request closed without merging**
